<?php

return [
    'definitions' => [
        'members_management' => [
            'label' => 'Members',
            'description' => 'Manage member profiles, plans, trainers, and lifecycle actions.',
            'group' => 'Core Operations',
            'icon' => 'users',
            'entry_route' => 'members.index',
        ],
        'trainers_management' => [
            'label' => 'Trainers',
            'description' => 'Manage trainers, schedules, and trainer assignments.',
            'group' => 'Core Operations',
            'icon' => 'trainer',
            'entry_route' => 'trainers.index',
        ],
        'membership_management' => [
            'label' => 'Membership',
            'description' => 'Create and manage gym membership plans for members.',
            'group' => 'Core Operations',
            'icon' => 'membership',
            'entry_route' => 'plans.index',
        ],
        'workout_management' => [
            'label' => 'Workouts',
            'description' => 'Handle workout sequences, plans, activities, and categories.',
            'group' => 'Training',
            'icon' => 'workout',
            'entry_route' => 'workout-sequences.index',
        ],
        'diet_management' => [
            'label' => 'Diet Plans',
            'description' => 'Create default and custom diet plans for members.',
            'group' => 'Training',
            'icon' => 'diet',
            'entry_route' => 'diet-plans.index',
        ],
        'ai_workout_plans' => [
            'label' => 'AI Workout Plans',
            'description' => 'Generate workout plans with AI. Uses workout data, but access is managed independently.',
            'group' => 'AI & Automation',
            'icon' => 'spark',
            'entry_route' => 'workout-sequences.index',
        ],
        'ai_diet_plans' => [
            'label' => 'AI Diet Plans',
            'description' => 'Generate diet plans with AI. Uses diet/member data, but access is managed independently.',
            'group' => 'AI & Automation',
            'icon' => 'spark',
            'entry_route' => 'diet-plans.index',
        ],
        'ai_track_user' => [
            'label' => 'AI Track User',
            'description' => 'Predict member churn risk, recommend offers, and explain reasons.',
            'group' => 'AI & Automation',
            'icon' => 'spark',
            'entry_route' => 'ai-track-user.index',
        ],
        'attendance_management' => [
            'label' => 'Attendance',
            'description' => 'Track check-ins and check-outs for member attendance.',
            'group' => 'Core Operations',
            'icon' => 'attendance',
            'entry_route' => 'attendance.index',
        ],
        'finance_management' => [
            'label' => 'Finance',
            'description' => 'Manage invoices, expenses, payments, and financial overview.',
            'group' => 'Business',
            'icon' => 'finance',
            'entry_route' => 'finance.index',
        ],
        'locker_management' => [
            'label' => 'Lockers',
            'description' => 'Manage locker inventory and assignments.',
            'group' => 'Business',
            'icon' => 'locker',
            'entry_route' => 'lockers.index',
        ],
        'event_management' => [
            'label' => 'Events',
            'description' => 'Manage events, event types, and calendar views.',
            'group' => 'Engagement',
            'icon' => 'event',
            'entry_route' => 'events.index',
        ],
        'whatsapp_updates' => [
            'label' => 'WhatsApp',
            'description' => 'Run WhatsApp campaigns and inspect WhatsApp delivery logs.',
            'group' => 'Notifications',
            'icon' => 'message',
            'entry_route' => 'whatsapp.campaigns.index',
        ],
        'advanced_reports' => [
            'label' => 'Reports',
            'description' => 'View members, revenue, and trainer reports.',
            'group' => 'Analytics',
            'icon' => 'reports',
            'entry_route' => 'reports.members',
        ],
        'notice_board' => [
            'label' => 'Notice Board',
            'description' => 'Create and manage gym-wide notices and updates.',
            'group' => 'Engagement',
            'icon' => 'notice',
            'entry_route' => 'notices.index',
        ],
        'contact_diary' => [
            'label' => 'Contact Diary',
            'description' => 'Track prospects, follow-ups, and contact history.',
            'group' => 'Engagement',
            'icon' => 'contact',
            'entry_route' => 'contact-diary.index',
        ],
        'body_progress' => [
            'label' => 'Body Progress',
            'description' => 'Track body stats and progress photos as a separate module.',
            'group' => 'Training',
            'icon' => 'progress',
            'entry_route' => 'body-stats.index',
        ],
        'online_payments' => [
            'label' => 'Online Payments',
            'description' => 'Use Razorpay and Stripe payment collection features.',
            'group' => 'Business',
            'icon' => 'payments',
            'entry_route' => 'finance.index',
        ],
        'multi_branch' => [
            'label' => 'Multi Branch',
            'description' => 'Reserved for managing multiple branches independently.',
            'group' => 'Enterprise',
            'icon' => 'branches',
            'entry_route' => null,
        ],
        'custom_branding' => [
            'label' => 'Custom Branding',
            'description' => 'Reserved for branch-specific or custom-branded experiences.',
            'group' => 'Enterprise',
            'icon' => 'branding',
            'entry_route' => 'settings.index',
        ],
        'api_access' => [
            'label' => 'API Access',
            'description' => 'Reserved for future external integration and developer API features.',
            'group' => 'Enterprise',
            'icon' => 'api',
            'entry_route' => null,
        ],
    ],

    'plan_defaults' => [
        'basic' => [
            'members_management',
            'trainers_management',
            'membership_management',
            'attendance_management',
            'notice_board',
            'contact_diary',
        ],
        'pro' => [
            'members_management',
            'trainers_management',
            'membership_management',
            'workout_management',
            'diet_management',
            'ai_track_user',
            'attendance_management',
            'finance_management',
            'locker_management',
            'event_management',
            'whatsapp_updates',
            'advanced_reports',
            'notice_board',
            'contact_diary',
            'body_progress',
            'online_payments',
        ],
        'enterprise' => [
            'members_management',
            'trainers_management',
            'membership_management',
            'workout_management',
            'diet_management',
            'ai_workout_plans',
            'ai_diet_plans',
            'ai_track_user',
            'attendance_management',
            'finance_management',
            'locker_management',
            'event_management',
            'whatsapp_updates',
            'advanced_reports',
            'notice_board',
            'contact_diary',
            'body_progress',
            'online_payments',
            'multi_branch',
            'custom_branding',
            'api_access',
        ],
    ],
];
